spring:
  application:
    name: shopit
  profiles:
    active: dev  # ?? ??? ?? dev ?? prod? ??

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/tdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user01
    password: pass01

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

server:
  port: 8001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: 5/9zjcargCY32h+xAQ5I/JICeDRAuBYa0o4LG15WjjSBg6rMyA6bPShtClaoJqAwKehlaZhgMaJqewfIi+FySw==
  expiration: 3000 #분단위

oauth:
  kakao:
    client-id: 059ef8f26b88dd1526613ba4725fd4ba  #카카오 REST API key
    redirect-uri: http://localhost:3000/oauth/kakao/redirect


---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: RDB URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_pass

  jpa:
    hibernate:
      ddl-auto: validate  # ??????? validate ?? none ??
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

server:
  port: 8001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true