spring:
  application:
    name: board
  datasource:
    hikari:
      url: jdbc:h2:tcp://localhost/경로/DB파일명
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8888